# Docker Compose for Development
# Provides consistent database and services for all developers
version: '3.8'

services:
  # Shared PostgreSQL database for development
  postgres-dev:
    image: postgres:15
    environment:
      POSTGRES_DB: ocs_tracker_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./dev_data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ocs-network

  # Tickets API
  tickets-api-dev:
    build: ./ocs-tickets-api
    environment:
      DATABASE_URL: postgresql://dev_user:dev_password@postgres-dev:5432/ocs_tracker_dev
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    depends_on:
      - postgres-dev
    networks:
      - ocs-network
    volumes:
      - ./ocs-tickets-api:/app

  # Portal
  portal-dev:
    build: ./ocs-portal-py
    environment:
      TICKETS_API_URL: http://tickets-api-dev:8000
      DATABASE_URL: postgresql://dev_user:dev_password@postgres-dev:5432/ocs_tracker_dev
      ENVIRONMENT: development
    ports:
      - "8080:8080"
    depends_on:
      - tickets-api-dev
    networks:
      - ocs-network
    volumes:
      - ./ocs-portal-py:/app

volumes:
  postgres_dev_data:

networks:
  ocs-network:
