version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ocs_user
      POSTGRES_PASSWORD: ocs_pass
      POSTGRES_DB: ocs_tickets
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ocs-tickets-api:
    build: ./ocs-tickets-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_tickets
    depends_on:
      - db
    volumes:
      - ./ocs-tickets-api:/app

  ocs-inventory-api:
    build: ./ocs-inventory-api
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_inventory
    depends_on:
      - db
    volumes:
      - ./ocs-inventory-api:/app

  ocs-requisition-api:
    build: ./ocs-requisition-api
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_requisition
    depends_on:
      - db
    volumes:
      - ./ocs-requisition-api:/app

  ocs-portal-py:
    build: ./ocs-portal-py
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_portal
    depends_on:
      - db
    volumes:
      - ./ocs-portal-py:/app

volumes:
  pgdata:
