version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ocs_user
      POSTGRES_PASSWORD: ocs_pass
      POSTGRES_DB: ocs_tickets
    ports:
      - "5433:5432" # Changed host port to 5433 to avoid conflict
    volumes:
      - pgdata:/var/lib/postgresql/data

  ocs-tickets-api:
    build:
      context: .
      dockerfile: ocs-tickets-api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_tickets
    depends_on:
      - db
  ocs-inventory-api:
    build:
      context: .
      dockerfile: ocs-inventory-api/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_inventory
    depends_on:
      - db

  ocs-purchasing-api:
    build:
      context: .
      dockerfile: ocs-purchasing-api/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_purchasing
    depends_on:
      - db

  ocs-portal-py:
    build:
      context: .
      dockerfile: ocs-portal-py/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_portal
    depends_on:
      - db
  ocs-manage-api:
    build:
      context: .
      dockerfile: ocs-manage/Dockerfile
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_manage
    depends_on:
      - db
  ocs-forms-api:
    build:
      context: .
      dockerfile: ocs-forms-api/Dockerfile
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgresql://ocs_user:ocs_pass@db:5432/ocs_forms
    depends_on:
      - db

volumes:
  pgdata:
